apiVersion: eksctl.io/v1beta
kind: ClusterConfig

metadata:
  name: go-app-deployment
  region: eu-west2

nodeGroups:
  - name: ng-1
    instanceType: t2.meduim
    desiredCapacity: 2
    volumeSize: 30
    #ssh:
     # allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
