apiVersion: v1
kind: deployment
metadata:
  name:  go-web-application
  labels: 
    app: go-web-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web-application
  template:
    metadata:
      labels:
        app: go-web-application
    spec:
      containers:
      - name: go-web-application
        image: lloyddigital/go-web-app:v1
        ports:
        - containerPort: 8080
        

