apiVersion: v1                      # Corrected the apiVersion
kind: Service
metadata:
  name: go-web-application
  labels: 
    app: go-web-application
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: go-web-application
  type: ClusterIP                   # Moved `type` to the correct location
