name: CI Workflow

# Controls when the workflow will run
on:
  push:
    branches:
      - main
    # Paths to ignore when updating values and not triggering the pipeline
    paths-ignore:
      - 'README.md'
      - 'helm/**'
  pull_request:
    branches:
      - main

# Define environment variables for the workflow
env:
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-application
  DOCKER_TAG: ${{ github.run_id }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go 1.22
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'

    - name: Run Tests
      run: go test ./...

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.56.2

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}

# Uncomment if you want to deploy
# deploy:
#   needs: build
#   runs-on: ubuntu-latest
#
#   steps:
#   - name: Checkout code
#     uses: actions/checkout@v3
#
#   - name: Deploy to Kubernetes
#     env:
#       KUBECONFIG: ${{ secrets.KUBECONFIG }}
#     run: |
#       kubectl set image deployment/go-web-application go-web-application=$DOCKER_IMAGE:$DOCKER_TAG
#       kubectl rollout status deployment/go-web-application

update-newtag-in-helm-chart:
  runs-on: ubuntu-latest
  needs: build

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.Token }}

    - name: Update tag in Helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{ env.DOCKER_TAG }}"/' helm/go-app-chart/values.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email 'lloydtheophilus@gmail.com'
        git config --global user.name 'lloyd-theophilus'
        git add helm/go-app-chart/values.yaml
        git commit -m 'Update tag in Helm chart'
        git push 
